#!/bin/bash
##    box
drawline () {
        declare line=""
        declare char="#"
        for (( i=0; i<$1; ++i )); do
                line="${line}${char}"
        done
        printf "%s\n" "$line"
}
[[ ! $1 ]] && exit 1
declare -i len="${#1} +16"
echo "#"
drawline len
printf "####    %s    ####\n" "$1"
drawline len
echo "#"
exit 0

